"""Migration to add previous_close_correct column to asset_metrics table

Revision ID: 20250825_001
Revises: 
Create Date: 2025-08-25 18:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20250825_001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_metrics', sa.Column('previous_close_correct', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_metrics', 'previous_close_correct')
    # ### end Alembic commands ###